### PR TITLE
Support objectSelector on mutating webhook

### PR DESCRIPTION
**Pull request by Cian911**
### 🛑 Important:
Please open an issue to discuss significant work before you start. We appreciate your contributions and don't want your efforts to go to waste!

For guidelines on how to contribute, please review the [CONTRIBUTING.md](CONTRIBUTING.md) document.

## Purpose of this PR

When the jobs are run for the `spark-operator` in the same namespace in which the operator resides, the operator will attempt to mutate itself. 

**Proposed changes:**
- This PR adds support for specifying an `objectSelector` on the `MutatingWebhookConfiguration` so as a user can specify _what_ pods matching a given set of labels the operator can mutate. See also related [issue](https://github.com/kubeflow/spark-operator/issues/1608) requesting this.
- ~This PR also updates the `minikube` CI action to the latest release.~ This has been moved to this [PR](https://github.com/kubeflow/spark-operator/pull/2059).

## Change Category
Indicate the type of change by marking the applicable boxes:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that could affect existing functionality)
- [ ] Documentation update

## Checklist
Before submitting your PR, please review the following:

- [x] I have conducted a self-review of my own code.
- [x] I have updated documentation accordingly.
- [x] I have added tests that prove my changes are effective or that my feature works.
- [x] Existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Cian911** [comment]
Looks like the CI failures caused as a result of minikube https://github.com/kubernetes/minikube/issues/18021

**Comment by yuchaoran2011** [comment]
This is a great addition. But can we limit each PR to a specific goal only (e.g. moving the CI action change to another PR)? That way, it's easier to troubleshoot and revert if needed.

**Comment by Cian911** [comment]
> This is a great addition. But can we limit each PR to a specific goal only (e.g. moving the CI action change to another PR)? That way, it's easier to troubleshoot and revert if needed.

Sure thing, I can move the CI change to a different PR. I just made the change to ensure the CI would pass. 

I'll do that now, which will need to be merged in first 👍

**Comment by Cian911** [comment]
@yuchaoran2011 I have removed the change from this PR (hence why some actions are failing), and moved it to this [PR](https://github.com/kubeflow/spark-operator/pull/2059). This new PR will need to be merged first, then this one rebased afterwards.

**Comment by vikas-saxena02** [comment]
> @yuchaoran2011 I have removed the change from this PR (hence why some actions are failing), and moved it to this [PR](https://github.com/kubeflow/spark-operator/pull/2059). This new PR will need to be merged first, then this one rebased afterwards.

Thanks @Cian911 I was just about to open another bug as the current CI is failing.  @yuchaoran2011 @andreyvelich @vara-bonthu  can we please merge this PR on a priority

**Comment by Cian911** [comment]
@yuchaoran2011 @vara-bonthu Now that my other PR has been merged with regards to the `minikube` CI issue, this PR should be good to go, if I can get a review/approval :pray:

**Comment by vara-bonthu** [comment]
PR looks good to me. Could you confirm if your local tests are successful?

**Comment by Cian911** [comment]
> PR looks good to me. Could you confirm if your local tests are successful?

Yes indeed, we are already using this in our clusters, see below:

Screenshot 2024-06-17 at 10 46 43

I've also just updated the chart version & docs again following the most recent merge. It would be great if any of you can review this again 🙇 cc: @vara-bonthu @yuchaoran2011

**Pull request merged**
