### PR TITLE
Add grafana dashboard to the helm chart

### PR DESCRIPTION
**Pull request by drazul**
Copy of PR https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1386
That PR was closed because one mistake when I rebased master

### CODE REVIEW

**Comment by rubenssoto** [comment]
I am testing your grafana dashboard, Do I have to do any configs on operator? Because the dashboard doesn't show any data.

**Comment by rubenssoto** [comment]
My prometheus show  owner_kind="<none>"

**Comment by drazul** [comment]
> I am testing your grafana dashboard, Do I have to do any configs on operator? Because the dashboard doesn't show any data.

I'm checking and almost all queries I use came from metrics-server and not from the operator metrics.

My metric server version is kube-state-metrics:v2.0.0

**Comment by tahesse** [comment]
Hey, I have done something similar with Influx & Grafana to monitor `{Scheduled,}SparkApplications` which populate their metrics via `spark.metrics.conf.*.sink.graphite.{class,host,port}` to an extra deployment of Influx which serves as a database to Grafana.

How does the Grafana dashboard play along with the [spark builtin history server](https://spark.apache.org/docs/3.1.1/monitoring.html#viewing-after-the-fact)?

Overall, I am really digging for this feature because imho it is superior to the history server in the context of k8s! I did not even know that the operator had a prometheus PodMonitor until I saw your PR! Thanks for the contribution! <3

**Comment by tahesse** [comment]
@liyinan926 any plans to merge this PR in the near future?

**Pull request closed without merging**
