### PR TITLE
chore: replace GoogleCloudPlatform/spark-on-k8s-operator with kubeflow/spark-operator

### PR DESCRIPTION
**Pull request by zevisert**
This is a naïve++ (as in, I did review each change) find and replace of the terms: 
- `GoogleCloudPlatform` => `kubeflow`
- `spark-on-k8s-operator` => `spark-operator`
- `GoogleCloudPlatform/spark-on-k8s-operator` => `kubeflow/spark-operator`
- `https://googlecloudplatform.github.io/spark-on-k8s-operator` => `https://kubeflow.github.io/spark-operator`

⚠️ I didn't try building anything or running any tests! I just wanted to get something up so that the migration from gcp's repo is addressed sooner than later. I also didn't change any documentation or anything.

- I also didn't update the ghcr.io references, that can be done in a PR for #1930 

Ref: #1929

### CODE REVIEW

**Comment by yuchaoran2011** [comment]
@zevisert Could you fix the DCO error as indicated in https://github.com/kubeflow/spark-operator/pull/1937/checks?check_run_id=22904525714?

**Comment by zevisert** [comment]
@yuchaoran2011, my commit message has been amended

**Comment by yuchaoran2011** [comment]
@zevisert Thanks. Please also fix the merge conflicts

**Comment by zevisert** [comment]
@yuchaoran2011 Done

**Comment by zevisert** [comment]
Actually, I rebased on master and found one more reference, I need one more commit

**Review by yuchaoran2011 — APPROVED** [review]
/lgtm

**Comment by vara-bonthu** [comment]
@zevisert Thanks for the PR! I noticed changes to Go files. Could you please confirm if you've had a chance to test those changes? If not, we could create an issue to validate and we can also look at addressing our e2e tests?

**Comment by zevisert** [comment]
@vara-bonthu No, I tried to make that clear in the description; this was just a find and replace. Were there no tests run as part of this PR?

**Comment by vzhao12** [comment]
This pr breaks all old images pull because in https://github.com/kubeflow/spark-operator/pkgs/container/spark-operator. There is no old version image available at all. Can you revert this pr or copy all image to the new place? Thanks

**Comment by vzhao12** [comment]
Please see the issue [here](https://github.com/kubeflow/spark-operator/issues/1991). I don't think I will be the only one who has this issue.

**Comment by zevisert** [comment]
@vzhao12 - I purposely didn't change the repository in this PR so as to not create issues like this. PR #1956 and PR #1974 have both changed the chart repository, but this PR did not.

**Pull request merged**
