### PR TITLE
added arm64 support, setup argo SA in multiple NS, spark 3.5.0

### PR DESCRIPTION
**Pull request by AndrewChubatiuk**
- replaced sparkJobNamespace with sparkJobNamespaces, spark role and rolebinding to cluster alternatives and added loop for SA to be able to support multiple namespaces for spark jobs
- upgraded spark image 3.1.1 to 3.5.0
- added arm64 support

### CODE REVIEW

**Comment by AndrewChubatiuk** [comment]
@zevisert could you please help with a review?

**Comment by zevisert** [comment]
> @zevisert could you please help with a review?

Sure, I might have some time after work tonight - no promises. Also, I'm not a maintainer here so I have no authority to approve your PR

**Review by yuchaoran2011 — CHANGES_REQUESTED** [review]
Thanks @AndrewChubatiuk for the contribution. Please split this PR into multiple ones. Each PR needs to have a single feature/bug fix/improvement for ease of review

**Comment by AndrewChubatiuk** [comment]
@yuchaoran2011 
https://github.com/kubeflow/spark-operator/pull/1954

**Comment by AndrewChubatiuk** [comment]
@yuchaoran2011 
https://github.com/kubeflow/spark-operator/pull/1956

**Comment by AndrewChubatiuk** [comment]
closing this in a favour of https://github.com/kubeflow/spark-operator/pull/1955

**Pull request closed without merging**
