### PR TITLE
Reintroduce option webhook.enable

### LINKED ISSUE #2137: [QUESTION] Spark-Operator deprecation on envVars
Hi,

I'm part of a team that deployed Spark Operator (v1beta2-1.6.1-3.5.0) on a highly secured internally managed Kubernetes cluster where webhooks are completely forbidden (amongst other things).

We're relying heavily on envVars for our Spark Application deployments and I was wondering : 
 - Why this feature was marked as deprecated
 - On which version/ApiVersion will it be removed ?

In the case of a removal, is there any workaround or other method implemented (knowing that webhooks aren't an option) ?

Thanks !

### PR DESCRIPTION
**Pull request by ChenYi015**
## Purpose of this PR

Close #2137.

**Proposed changes:**
- Reintroduce option `webhook.enable`
- The webhook is enabled by default, but users can choose to disable the webhook server when webhooks are forbidden in K8s

## Change Category
Indicate the type of change by marking the applicable boxes:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that could affect existing functionality)
- [ ] Documentation update

## Checklist
Before submitting your PR, please review the following:

- [x] I have conducted a self-review of my own code.
- [ ] I have updated documentation accordingly.
- [x] I have added tests that prove my changes are effective or that my feature works.
- [x] Existing unit tests pass locally with my changes.

### CODE REVIEW

**Review by vara-bonthu — APPROVED** [review]
It's important to have the option to enable or disable webhooks. Many organizations face restrictions when it comes to enabling them in their Kubernetes environments.

**Review by jacobsalway — APPROVED** [review]
LGTM. The change is simple but I tested locally with `webhook.enable=false` with Kind and only the controller is spin up as expected.

**Review by vara-bonthu — APPROVED** [review]
/lgtm

**Pull request merged**
