### PR TITLE
feat: add support for custom service labels

### PR DESCRIPTION
**Pull request by Cian911**
There is no way currently to add custom labels to services created by the `spark-operator`. This can be very useful for anyone who uses [opa-gatekeeper](https://github.com/open-policy-agent/gatekeeper) for policy controls in their kubernetes clusters.

See related issues of users asking for this: https://github.com/kubeflow/spark-operator/issues/1342

### CODE REVIEW

**Review by yuchaoran2011 — CHANGES_REQUESTED** [review]
Thanks for the contribution. Indentation has issues. Please make sure to run `go fmt` to reformat the code. `serviceLabels` sounds generic. Can we make it clear by renaming it to something like `sparkUiSvcLabels`?

**Comment by Cian911** [comment]
> Thanks for the contribution. Indentation has issues. Please make sure to run `go fmt` to reformat the code. `serviceLabels` sounds generic. Can we make it clear by renaming it to something like `sparkUiSvcLabels`?

@yuchaoran2011 Thanks for taking a look, and the quick response. I have pushed a fix for the formatting :+1: 

However, with regards to renaming `serviceLabels`, I'm not sure I agree. The change I made, I feel, is adhering to the naming already in place for other attributes on the `SparkUIConfiguration` struct: [see here](https://github.com/Cian911/spark-operator/blob/9054d23ced1bbc171889f7b9ac069981a328ff37/pkg/apis/sparkoperator.k8s.io/v1beta2/types.go#L304).

I _can_ make this change if insisted, but I personally don't see the benefit in the following configuration (as this suggestion might entail):

```yaml
sparkUIOptions:
    sparkUiSvcLabels:
      test-label/v1: 'true'
``` 

vs

```yaml
sparkUIOptions:
    serviceLabels:
      test-label/v1: 'true'
```

**Review by yuchaoran2011 — CHANGES_REQUESTED** [review]
You are right. I missed that the newly added serviceLabels is under UI configurations. That's good then. One last change: another PR got merged before yours that took the 1.1.29 version number, now the chart number needs to be bump up to 1.1.30

**Comment by Cian911** [comment]
@yuchaoran2011 Done :)

**Review by yuchaoran2011 — APPROVED** [review]
/lgtm

**Pull request merged**
