### PR TITLE
Fixes a bug with dynamic allocation forcing the executor count to be 1 even when minExecutors is set to 0

### PR DESCRIPTION
**Pull request by peter-mcclonski**
### 🛑 Important:
Please open an issue to discuss significant work before you start. We appreciate your contributions and don't want your efforts to go to waste!

For guidelines on how to contribute, please review the [CONTRIBUTING.md](CONTRIBUTING.md) document.

## Purpose of this PR
Fixes a bug with dynamic allocation forcing the executor count to be 1 even when minExecutors is set to 0

## Change Category
Indicate the type of change by marking the applicable boxes:

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that could affect existing functionality)
- [ ] Documentation update

### Rationale

Resolves otherwise unexpected behavior where the value of minExecutors was not fully respected.

## Checklist
Before submitting your PR, please review the following:

- [X] I have conducted a self-review of my own code.
- [X] I have updated documentation accordingly.
- [X] I have added tests that prove my changes are effective or that my feature works.
- [X] Existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by peter-mcclonski** [comment]
Resolves #1779

**Comment by peter-mcclonski** [comment]
@vara-bonthu some quick feedback:
- The build-api-docs pre-commit check isn't possible to resolve in this case.  It's getting flagged because there is a code difference, but the difference isn't one that would be reflectable in the api docs.  Regenerating the api-docs results in no change.
- The Chart appVersion has been updated, but the build-helm-chart and build-spark-operator checks don't seem to know how to handle it.

Honestly not sure how to resolve these issues, since it looks like the actual resolution isn't being respected by the check.  Can you advise?

**Comment by vara-bonthu** [comment]
Did you try to rebase your PR branch with master and uplift the chat version?

**Comment by peter-mcclonski** [comment]
> Did you try to rebase your PR branch with master and uplift the chat version?

Yup, I had tried this previously but just re-attempted for the next time the workflow is run.  I don't think that will/would assist with the api-docs issue.

**Review by vara-bonthu — APPROVED** [review]
/approve

@yuchaoran2011 please review the PR

**Comment by peter-mcclonski** [comment]
@vara-bonthu Any hope of getting this merged soon?

**Comment by vara-bonthu** [comment]
Waiting for another approval from @yuchaoran2011

**Pull request merged**
