### PR TITLE
Chart: add patch permissions for spark operator SA to support spark 3.5.0

### PR DESCRIPTION
**Pull request by Aakcht**
While trying to run spark operator with Spark 3.5.0, I noticed the following errors:

```
Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. services "spark-pi-test-run-1-72fa8a8c0fd5639e-driver-svc" is forbidden: User "system:serviceaccount:spark:sparkoperator-spark-spark-operator" cannot patch resource "services" in API group "" in the namespace "spark-test-apps".
 at io.fabric8.kubernetes.client.KubernetesClientException.copyAsCause(KubernetesClientException.java:238)
 at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:518)
 at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:535)
 at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handlePatch(OperationSupport.java:430)
 at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handlePatch(OperationSupport.java:408)
 at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handlePatch(BaseOperation.java:713)
 at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.lambda$patch$2(HasMetadataOperation.java:232)
 at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.patch(HasMetadataOperation.java:237)
 at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.patch(HasMetadataOperation.java:252)
 at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.serverSideApply(BaseOperation.java:1132)
 at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.serverSideApply(BaseOperation.java:92)
 at io.fabric8.kubernetes.client.extension.ResourceAdapter.serverSideApply(ResourceAdapter.java:325)
 at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
 at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
 at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
 at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
 at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
 at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
 at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
 at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.performOperation(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:294)
 at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.serverSideApply(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:324)
 at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.serverSideApply(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:55)
 at org.apache.spark.deploy.k8s.submit.Client.run(KubernetesClientApplication.scala:176)
 at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.$anonfun$run$6(KubernetesClientApplication.scala:256)
 at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.$anonfun$run$6$adapted(KubernetesClientApplication.scala:250)
 at org.apache.spark.util.SparkErrorUtils.tryWithResource(SparkErrorUtils.scala:48)
 at org.apache.spark.util.SparkErrorUtils.tryWithResource$(SparkErrorUtils.scala:46)
 at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:94)
 at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.run(KubernetesClientApplication.scala:250)
 at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.start(KubernetesClientApplication.scala:223)
 at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:1029)
 at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
 at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
 at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
 at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
 at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
 at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
...
```

and

```
Forbidden!Configured service account doesn't have access. Service account may have been revoked. configmaps "spark-drv-415b968c103c268a-conf-map" is forbidden: User "system:serviceaccount:spark:sparkoperator-spark-spark-operator" cannot patch resource "configmaps" in API group "" in the namespace "spark-test-apps".
```

These errors cause spark applications to fail. 

So I added the `patch` permissions to spark-operator service account - with this change spark applications run successfully with Spark 3.5.0 .

### CODE REVIEW

**Comment by zevisert** [comment]
This diff is duplicated by #1908, but since this provides a traceback, I think this is the better PR to merge just based on the fact that if anyone needs to come looking, there's more information available here.

**Review by yuchaoran2011 — CHANGES_REQUESTED** [review]
It will be great to get this fix it. @Aakcht the Helm chart build failed. Could you bump up the version number in Chart.yaml?

**Comment by Aakcht** [comment]
@yuchaoran2011, I bumped the version, but looks like the build is still failing, not sure why :( Any ideas?

**Comment by Aakcht** [comment]
Checked in master branch - looks like there is something wrong with the master branch, since the problem checks failed for all latest commits in master.

**Comment by yuchaoran2011** [comment]
I see these build errors that are not related to your PR:
```
ERROR: failed to solve: gcr.io/spark-operator/spark:v3.1.1: gcr.io/spark-operator/spark:v3.1.1: not found
```
```
  make helm-docs
  if ! git diff --quiet -- charts/spark-operator-chart/README.md; then
    echo "Need to re-run 'make helm-docs' and commit the changes"
    false
  fi
  shell: /usr/bin/bash -e {0}
docker: invalid spec: :/helm-docs: empty section between colons.
See 'docker run --help'.
make: *** [Makefile:48: helm-docs] Error 125
Error: Process completed with exit code 2.
```
Let me approve and see if the system can merge it despite these errors

**Review by yuchaoran2011 — APPROVED** [review]
/lgtm

**Comment by Aakcht** [comment]
Looks like that wasn't enough :( Not sure how `tide` check works, maybe it is possible to make other problem checks not required?

**Comment by yuchaoran2011** [comment]
We need to fix the CI pipelines. This issue needs to be prioritized: https://github.com/kubeflow/spark-operator/issues/1930. If you are interested, don't hesitate to take a stab at it cc' @vara-bonthu

**Comment by Aakcht** [comment]
Hi, @yuchaoran2011! Please take a look, I noticed that the pipeline is already fixed, so I did another rebase to fix the conflicts regarding chart version.

**Pull request merged**
