### PR TITLE
Update spark operator permissions for CRD

### LINKED ISSUE #1960: The spark operator does not need create, update and delete permissions for CustomResourceDefinition
The RBAC resources for the spark operator currently have permissions to `create`, `get`, `update` and `delete` `CustomResourceDefinition`:

https://github.com/kubeflow/spark-operator/blob/69e984135217146f321f46db9ab0fd1ee3340fcb/charts/spark-operator-chart/templates/rbac.yaml#L66-L74

However, permissions for `CustomResourceDefinition` are only required by Volcano scheduler integrated in spark operator, and it solely requires the `get` permission. 

https://github.com/kubeflow/spark-operator/blob/69e984135217146f321f46db9ab0fd1ee3340fcb/pkg/batchscheduler/volcano/volcano_scheduler.go#L176-L204

For enhanced security, it would be more appropriate to modify the permissions as follows:

```yaml
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
```

### PR DESCRIPTION
**Pull request by ChenYi015**
## Purpose of this PR

Close #1960 

**Proposed changes:**
- spark operator rbac: remove the `create`, `update` and `delete` permissions for CustomResourceDefinition

## Change Category
Indicate the type of change by marking the applicable boxes:

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that could affect existing functionality)
- [ ] Documentation update

### Rationale

The reason is described in #1960 .

## Checklist
Before submitting your PR, please review the following:

- [x] I have conducted a self-review of my own code.
- [ ] I have updated documentation accordingly.
- [ ] I have added tests that prove my changes are effective or that my feature works.
- [ ] Existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by vara-bonthu** [comment]
/approve

👍🏼 for anything that helps to improve the security of the Spark Operator deployment

**Review by vara-bonthu — APPROVED** [review]
/lgtm

**Comment by vara-bonthu** [comment]
@ChenYi015 Please resolve the conflicts

**Review by yuchaoran2011 — APPROVED** [review]
/lgtm

**Comment by yuchaoran2011** [comment]
@ChenYi015 could you fix this CI error?
```
Need to re-run 'make helm-docs' and commit the changes
```

**Comment by ChenYi015** [comment]
> @ChenYi015 could you fix this CI error?
> 
> ```
> Need to re-run 'make helm-docs' and commit the changes
> ```

fixed

**Review by yuchaoran2011 — APPROVED** [review]
/lgtm

**Pull request merged**
