### PR TITLE
Add workflow for closing stale issues and PRs

### PR DESCRIPTION
**Pull request by ChenYi015**
## Purpose of this PR

Add workflow for closing staled issues and PRs:
- The issues/PRs will be marked as stale for 60 days with no activity and will be closed after 30 days with no activity.

## Change Category
Indicate the type of change by marking the applicable boxes:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that could affect existing functionality)
- [ ] Documentation update

## Checklist
Before submitting your PR, please review the following:

- [x] I have conducted a self-review of my own code.
- [ ] I have updated documentation accordingly.
- [ ] I have added tests that prove my changes are effective or that my feature works.
- [ ] Existing unit tests pass locally with my changes.

### CODE REVIEW

**Review by vara-bonthu — APPROVED** [review]
Thanks for adding this. I believe it's essential for maintaining the repo and encourages contributors to reopen PRs and issues if they still think they are necessary. Given the many open PRs and issues, this could close most of them.

I want to ensure all maintainers and reviewers are okay with this approach.
@yuchaoran2011 @andreyvelich

**Comment by yuchaoran2011** [comment]
This will be a good topic for the community meeting next week. Let's gather more input before making a decision

**Comment by yuchaoran2011** [comment]
As discussed during the most recent community call, attendees have agreed on giving this new process of managing issues and PRs a try
/lgtm

**Review by yuchaoran2011 — APPROVED** [review]
/lgtm

**Pull request merged**
