### PR TITLE
[MERGE] Adding support for cert-manager certificates to manage webhook TLS

### PR DESCRIPTION
**Pull request by YanivKunda**
This PR clones https://github.com/kubeflow/spark-operator/pull/1567, with the following:
1. Merging the changes [dskatz:feature/certmanager](https://github.com/dskatz/spark-on-k8s-operator/tree/feature/certmanager)
2. Resolving conflicts (keeping `webhook-cleanup-job.yaml` & `webhook-init-job.yaml` deleted)
3. Upgrading `cert-manager.io` apiVersion to v1
4. Bumping operator app and chart versions

### CODE REVIEW

**Comment by yuchaoran2011** [comment]
@YanivKunda Thanks for porting over the PR! Please fix the failed CI checks and DCO, then it should be good to be merged

**Review by ChenYi015 — CHANGES_REQUESTED** [review]
Thanks for the PR, I have left some comments.

**Comment by YanivKunda** [comment]
Replaced by https://github.com/kubeflow/spark-operator/pull/2083 due to messy merge and trailers

**Comment by YanivKunda** [comment]
> @YanivKunda Thanks for porting over the PR! Please fix the failed CI checks and DCO, then it should be good to be merged

@yuchaoran2011 if you want to continue this under https://github.com/kubeflow/spark-operator/pull/2083

**Pull request closed without merging**
