### PR TITLE
chore: remove k8s.io/kubernetes replaces and adapt to v1.29.3 apis

### PR DESCRIPTION
**Pull request by ajayk**

### CODE REVIEW

**Comment by ajayk** [comment]
cc @AndrewChubatiuk

**Comment by vara-bonthu** [comment]
@ajayk, it looks like the PR description is missing. Could you please provide more details to help us review your changes effectively? 

**Purpose of the Change:** Why is this change necessary?
**Problem Addressed:** What issue are you encountering that this change resolves?
**Solution:** How does this change solve the problem?
**Impact of Not Merging:** What would be the consequences if this PR is not merged?
**Existing Workarounds:** Is there a current workaround for this issue, and if so, what are its drawbacks?


Thank you for contributing, and we look forward to your detailed response!

**Comment by debasishbsws** [comment]
@vara-bonthu It seems to me that while upgrading the k8s.io/kubernetes module version in PR: https://github.com/kubeflow/spark-operator/pull/1630 the person missed removing the replace statement present in go.mod file for Kubernetes https://github.com/kubeflow/spark-operator/blob/6ded3acd1c5058c1d737e40d6135b5606dc68e43/go.mod#L161

For this reason, even after Updating the module version in #1630 #1954, it is set to version 1.19.6, Which is 10 versions older than the current one 1.29.3 [link](https://github.com/kubeflow/spark-operator/pull/1954/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R29). This older version of Kubernetes has multiple CVE present in it.

just removing the replace line doesn't fix as there is a version mismatch with some other go modules this PR try to fix those with minimal changes.

**Review by yuchaoran2011 — APPROVED** [review]
Good catch! /lgtm

**Pull request merged**
