### PR TITLE
fix: fixed serviceaccount annotations

### PR DESCRIPTION
**Pull request by AndrewChubatiuk**
## Purpose of this PR
Fixed serviceaccount annotations

## Change Category
Indicate the type of change by marking the applicable boxes:

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that could affect existing functionality)
- [x] Documentation update

## Checklist
Before submitting your PR, please review the following:

- [x] I have conducted a self-review of my own code.
- [x] I have updated documentation accordingly.
- [x] I have added tests that prove my changes are effective or that my feature works.
- [x] Existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by AndrewChubatiuk** [comment]
@vara-bonthu could you please review?

**Comment by vara-bonthu** [comment]
Thank you for the PR, @AndrewChubatiuk. Could you please update the documentation to reflect this change? Here's the section that needs updating: [Quick Start Guide - About the Spark Job Namespace](https://github.com/kubeflow/spark-operator/blob/master/docs/quick-start-guide.md#about-the-spark-job-namespace).

I notice that you've improved an existing feature. However, users can already create their own namespaces with dedicated IAM roles and service accounts outside of the Spark Operator's scope to run jobs in a multi-tenancy setup. Does this feature truly simplify the user journey?

**Comment by AndrewChubatiuk** [comment]
@vara-bonthu this is an optional feature, it just adds ability to create namespaces. It's useful in a setup we're using, we do not manage spark job namespaces independently

**Review by vara-bonthu — APPROVED** [review]
/approve

Let's wait for another approval since it's a breaking change

**Comment by yuchaoran2011** [comment]
We use this feature: have Spark operator manage multiple application namespaces and rely on the operator chart to create the application service account and roles. That said, I'm not sure if it's a good idea to get the chart to be involved in namespace creation. I believe the standard practice is to not let chart do it

**Comment by AndrewChubatiuk** [comment]
@yuchaoran2011 okay, left only annotations fix for serviceaccount

**Comment by AndrewChubatiuk** [comment]
@yuchaoran2011 okay, renamed PR and left only annotations fix for serviceaccount

**Review by yuchaoran2011 — COMMENTED** [review]
Thanks, CI is failing though. Please fix the error reported in https://github.com/kubeflow/spark-operator/actions/runs/8712244183/job/23898100857?pr=1972

**Review by yuchaoran2011 — APPROVED** [review]
/lgtm

**Comment by AndrewChubatiuk** [comment]
@yuchaoran2011 fixed

**Pull request merged**
