### PR TITLE
fixed missing driver/executor ports schema in sparkapplication crd

### PR DESCRIPTION
**Pull request by oscar-dela**
Issue: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1404

### CODE REVIEW

**Comment by liyinan926** [comment]
Please update the chart version.

**Comment by oscar-dela** [comment]
@liyinan926 thanks for reminding, bumped to 1.1.22 now.

**Comment by liyinan926** [comment]
Looks like you need to bump the version again.

**Comment by oscar-dela** [comment]
Updated

**Comment by liyinan926** [comment]
Sorry about it, but looks like another conflict in Chart.yaml needs to be resolved.

**Comment by mattdornfeld** [comment]
Any plan to merge this? It would be great to have support for opening custom ports.

**Comment by oscar-dela** [comment]
@liyinan926 updated. please help to review again. Thanks

**Comment by sakshambhatla** [comment]
This has been open since a month. Can we do something to speed up the merge?

**Comment by hiradha** [comment]
We also need this. Can someone please merge this? Thanks

**Comment by vara-bonthu** [comment]
@oscar-dela please update the helm chart version to latest so that we can review and merge. Thanks

**Comment by LIN-Yu-Ting** [comment]
@vara-bonthu @oscar-dela, It seems that this project defines its own [Port struct](https://github.com/atgenomix/spark-operator/blob/72b1c180430db3e7965c699c0cb5742d064f8d05/pkg/apis/sparkoperator.k8s.io/v1beta2/types.go#L678) in both driver and executor, which is different from Port defined in apiv1. I am doubting that just by modifying two crds files can solve this issue.

**Comment by LIN-Yu-Ting** [comment]
@vara-bonthu. Could you please give some suggestions on my local trials to modify crds ? Actually, I tried to add following ports definition between [podSecurityContext and schedulerName](https://github.com/kubeflow/spark-operator/blob/5a5983b1ae3fc760ca5b9a2bab3549a7ee130b31/charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml#L1247). 

```
ports:
  items:
    properties:
      name:
        type: string
      protocol:
        type: string
      containerPort:
        type: integer
    required:
    - name
    - protocol
    - containerPort
    type: object
```

Following the [developer guide](https://github.com/kubeflow/spark-operator/blob/master/docs/developer-guide.md), I did successfully run the command ```hack/update-codegen.sh
``` and rebuild the Docker image which I use to install spark-operator with helm command ```helm install my-release spark-operator/spark-operator --namespace spark-operator --create-namespace --set sparkJobNamespace=default --set webhook.enable=true --set image.repository=ghcr.io/atgenomix/spark-operator --set image.tag=test```.  For 

However, I continue to receive following error messages, which seems that modification of sparkoperator.k8s.io_sparkapplications.yaml does not take any effect.

```
Error from server (BadRequest): error when creating "spark-pi.yaml": SparkApplication in version "v1beta2" cannot be handled as a SparkApplication: strict decoding error: unknown field "spec.executor.ports"
```

After I execute ```hack/update-codegen.sh```, I got some pkg files modified. However, nothing related to the modification of sparkoperator.k8s.io_sparkapplications.yaml.  I am wondering whether there is anything I missed.
```
linyuting@lindembp spark-operator % git status
開頭指標分離自 5a5983b
尚未暫存以備提交的變更：
  （使用 "git add <檔案>..." 更新要提交的內容）
  （使用 "git restore <檔案>..." 捨棄工作區的改動）
	修改：     go.mod
	修改：     go.sum
	修改：     pkg/apis/sparkoperator.k8s.io/v1beta2/zz_generated.deepcopy.go
	修改：     pkg/client/clientset/versioned/clientset.go
	修改：     pkg/client/clientset/versioned/fake/clientset_generated.go
	修改：     pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1beta1/fake/fake_scheduledsparkapplication.go
	修改：     pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1beta1/fake/fake_sparkapplication.go
	修改：     pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1beta1/sparkoperator.k8s.io_client.go
	修改：     pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1beta2/fake/fake_scheduledsparkapplication.go
	修改：     pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1beta2/fake/fake_sparkapplication.go
	修改：     pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1beta2/sparkoperator.k8s.io_client.go
	修改：     pkg/client/informers/externalversions/factory.go
```

Thanks in advance for any comments and discussion.

**Comment by 1350lumen** [comment]
> @vara-bonthu @oscar-dela, It seems that this project defines its own [Port struct](https://github.com/atgenomix/spark-operator/blob/72b1c180430db3e7965c699c0cb5742d064f8d05/pkg/apis/sparkoperator.k8s.io/v1beta2/types.go#L678) in both driver and executor, which is different from Port defined in apiv1. I am doubting that just by modifying two crds files can solve this issue.

The webhook has the code which updates the pod manifests with Ports defined in the CRD https://github.com/kubeflow/spark-operator/blob/v1beta2-1.6.1-3.5.0/pkg/webhook/patch.go#L406

**Pull request closed without merging**
