### PR TITLE
[WIP] add documentation for airflow-integration

### PR DESCRIPTION
**Pull request by roitvt**
this addresses https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/502

### CODE REVIEW

**Comment by andizzle** [comment]
How exactly should I install this in airflow? I know the doc in WIP but I don't see anything in code doc either.

So far I tried `airflow-providers-google[cncf.kubernetes]` according to https://github.com/apache/airflow/blob/1.10.10/CONTRIBUTING.rst#backport-providers-packages but no luck.

**Comment by andizzle** [comment]
I managed to install this for airflow 1.10.*, I have to compile the backport packages from the airflow source repo with 
```
./scripts/ci/ci_prepare_packages.sh cncf.kubernetes
```

Then install with pip
```
pip install dist/apache_airflow_providers_cncf_kubernetes-0.0.1-py2.py3-none-any.whl
```

**Comment by roitvt** [comment]
@andizzle Awesome!!! hopefully, airflow will release the official backported packages soon :)

**Comment by liyinan926** [comment]
@roitvt will you have some time to finish this PR?

**Comment by roitvt** [comment]
@liyinan926 I waited for airflow to release the integration in backport version for the current airflow 1.10 they told me today that it will happen really soon, yes I'll try to finish it this week

**Comment by janarthanandev** [comment]
@roitvt Any

> 
> 
> @liyinan926 I waited for airflow to release the integration in backport version for the current airflow 1.10 they told me today that it will happen really soon, yes I'll try to finish it this week

@roitvt Thanks for huge contribution. we were using airflow V1.10.10 it will be great if it was happen. Can you please update the status

**Comment by alextarasov-spot** [comment]
@roitvt do you have plans to finish this doc?  Thanks.

**Comment by zevisert** [comment]
Given that there was no response in 3 years, this should be closed now.

**Pull request closed without merging**
