### PR TITLE
support multiple namespaces

### PR DESCRIPTION
**Pull request by AndrewChubatiuk**
replaced sparkJobNamespace with sparkJobNamespaces, added creation of spark role, serviceaccount and rolebinding for every spark job namespace

### CODE REVIEW

**Review by yuchaoran2011 — CHANGES_REQUESTED** [review]
I'm not sure if changing Roles and RoleBindings to ClusterRoles and ClusterRoleBindings respectively is a good idea. RBAC permissions should be as tight as possible for security reasons. It's better to create a role and role binding for each application namespace

**Comment by AndrewChubatiuk** [comment]
> I'm not sure if changing Roles and RoleBindings to ClusterRoles and ClusterRoleBindings respectively is a good idea. RBAC permissions should be as tight as possible for security reasons. It's better to create a role and role binding for each application namespace

Changed to Role and RoleBinding loop

**Review by yuchaoran2011 — COMMENTED** [review]
Could you add more details to how this PR was tested? Specifically, it will be good to verify that webhook still works as expected. Some web hook resources are namespace specific. I don't remember which ones off the top of my head, but the webhook service and MutatingWebhookConfiguration objects are good to validate

**Comment by AndrewChubatiuk** [comment]
@yuchaoran2011 I've beed running it in my project for several month in such setup. I see mutatingwebhooks for pods only and it monitors namespaces depending on operator's `-namespace`

**Comment by AndrewChubatiuk** [comment]
it makes sense to migrate operator to kubebuilder v4, it simplifies setup and management a lot and also reduces amount of code lines

**Comment by AndrewChubatiuk** [comment]
@yuchaoran2011 do you expect any other changes here?

**Review by yuchaoran2011 — APPROVED** [review]
/lgtm

**Pull request merged**
