### PR TITLE
Use Kubeflow Docker Hub for Spark Operator Image

### PR DESCRIPTION
**Pull request by andreyvelich**
As we discussed, I used Kubeflow Docker Hub for Spark Operator images.

/assign @vara-bonthu @yuchaoran2011

### CODE REVIEW

**Comment by vara-bonthu** [comment]
Thanks for the PR, @andreyvelich! I've observed that ghcr.io has been used as the container registry in recent PRs. Should we stick with `ghcr.io` or consider switching to `docker.io` ? What do you think?

@yuchaoran2011, @ChanYiLin, @andreyvelich, what are your thoughts on this?

**Comment by andreyvelich** [comment]
> Thanks for the PR, @andreyvelich! I've observed that ghcr.io has been used as the container registry in recent PRs. Should we stick with `ghcr.io` or consider switching to `docker.io` ? What do you think?
> 
> @yuchaoran2011, @ChanYiLin, @andreyvelich, what are your thoughts on this?

Right now, we target to use Kubeflow Docker Hub to push most of our images. For example, recently the new Kubeflow Model Registry updated their CI/CD to publish images to the Kubeflow Docker Hub: https://github.com/kubeflow/model-registry/blob/main/.github/workflows/build-and-push-image.yml#L16-L21.

Training Operator also uses Kubeflow Docker Hub: https://github.com/kubeflow/training-operator/blob/master/.github/workflows/build-and-publish-images.yaml#L52-L56

In the meantime, we are working with the various Kubeflow working groups to figure out what image registry we should use for the long-term.

**Review by vara-bonthu — APPROVED** [review]
/approve

**Comment by vara-bonthu** [comment]
@andreyvelich you may need to run `pre-commit` locally to fix the failed checks https://github.com/kubeflow/spark-operator/blob/master/docs/developer-guide.md#configure-git-pre-commit-hooks

@yuchaoran2011 Please review the PR

**Review by yuchaoran2011 — APPROVED** [review]
/lgtm

**Comment by andreyvelich** [comment]
I've rebased my PR, now the CI/CD looks good.

**Review by vara-bonthu — APPROVED** [review]
/lgtm

**Review by yuchaoran2011 — APPROVED** [review]
/lgtm

**Pull request merged**
