### PR TITLE
Added jacobsalway as a reviewer

### PR DESCRIPTION
**Pull request by yuchaoran2011**
### 🛑 Important:
Please open an issue to discuss significant work before you start. We appreciate your contributions and don't want your efforts to go to waste!

For guidelines on how to contribute, please review the [CONTRIBUTING.md](CONTRIBUTING.md) document.

## Purpose of this PR
[jacobsalway](https://github.com/jacobsalway) has been consistently making quality contributions to the project. Adding him as a reviewer.

## Change Category
Indicate the type of change by marking the applicable boxes:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that could affect existing functionality)
- [ ] Documentation update

## Checklist
Before submitting your PR, please review the following:

- [ ] I have conducted a self-review of my own code.
- [ ] I have updated documentation accordingly.
- [ ] I have added tests that prove my changes are effective or that my feature works.
- [ ] Existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by ChenYi015** [comment]
@yuchaoran2011 Could you sign the commit by 'git commit -s -m "xxx"' to pass the DCO check?

**Comment by jacobsalway** [comment]
I'll raise a PR to add myself to the Kubeflow org

**Comment by yuchaoran2011** [comment]
@ChenYi015 Thanks for catching that. Now fixed. I guess we'll wait for @jacobsalway to add himself to kubeflow org before proceeding with this PR

**Comment by jacobsalway** [comment]
PR here https://github.com/kubeflow/internal-acls/pull/702

**Review by vara-bonthu — APPROVED** [review]
Thank you for all your contributions, @jacobsalway! 🙌🏼 I'm glad to see you on board as a reviewer.

**Comment by andreyvelich** [comment]
Thank you for all of your great contributions @jacobsalway!
/lgtm

**Pull request merged**
