### PR TITLE
fix: upgraded k8s deps

### PR DESCRIPTION
**Pull request by AndrewChubatiuk**
upgraded k8s deps after https://github.com/kubeflow/spark-operator/pull/1968
fixed docs generation

### CODE REVIEW

**Review by yuchaoran2011 — COMMENTED** [review]
@AndrewChubatiuk Please follow the PR template to include more details in the PR description. Specifically, why is the PR needed and what's the impact (e.g. it's needed to make operator run on k8s version x and it will drop support for k8s version y)

**Comment by AndrewChubatiuk** [comment]
after recent change in master upgraded depdendencies to fix CI pipeline also it decreases binary size

**Comment by AndrewChubatiuk** [comment]
@yuchaoran2011 after recent change in master upgraded depdendencies to fix CI pipeline also it decreases binary size

**Review by yuchaoran2011 — APPROVED** [review]
/lgtm

**Pull request merged**
