### PR TITLE
Release v2.0.0-rc.0

### PR DESCRIPTION
**Pull request by ChenYi015**
## Purpose of this PR

Release Spark operator `v2.0.0-rc.0`. 

Given that this is the first version of Spark Operator after improving the release process #2089, let me elaborate on the details:

1. Upon merging this PR, a Git tag corresponding to the version specified in the `VERSION` file (specifically, `v2.0.0-rc.0`) will be automatically created and pushed, provided it does not already exist.
2. Following the git tag's push, one workflow detailed in [release-docker.yaml](https://github.com/kubeflow/spark-operator/blob/release-2.0/.github/workflows/release-docker.yaml) will be triggered to publish the Docker image with tag `2.0.0-rc.0`(without prefix `v`).
3. Concurrently, another workflow detailed in [release.yaml](https://github.com/kubeflow/spark-operator/blob/release-2.0/.github/workflows/release.yaml) will be triggered to create a draft release, with the helm chart packaged as a artifact. 
4. Then, we will edit the release notes and finally publish the release.
5. Once the release is published, one workflow detailed in [release-charts.yaml](https://github.com/kubeflow/spark-operator/blob/release-2.0/.github/workflows/release-charts.yaml) will be triggered to update the Helm repo index file [index.yaml](https://github.com/kubeflow/spark-operator/blob/gh-pages/index.yaml).

### CODE REVIEW

**Review by yuchaoran2011 — APPROVED** [review]

**Review by vara-bonthu — APPROVED** [review]
/lgtm

**Comment by ChenYi015** [comment]
Hi @andreyvelich. I had met some problems while releasing Spark operator. After this PR was merged, the tag `v2.0.0-rc.0`  was successfully created and pushed by the [workflow](https://github.com/kubeflow/spark-operator/actions/runs/10314052997). However, another two workflows [release-docker.yaml](https://github.com/kubeflow/spark-operator/blob/release-2.0/.github/workflows/release-docker.yaml) and [release.yaml](https://github.com/kubeflow/spark-operator/blob/release-2.0/.github/workflows/release.yaml) were not triggered by this tag push event as expected. And I cannot figure out why, perhaps you could offer me some guidance.

**Comment by andreyvelich** [comment]
> Hi @andreyvelich. I had met some problems while releasing Spark operator. After this PR was merged, the tag `v2.0.0-rc.0` was successfully created and pushed by the [workflow](https://github.com/kubeflow/spark-operator/actions/runs/10314052997). However, another two workflows [release-docker.yaml](https://github.com/kubeflow/spark-operator/blob/release-2.0/.github/workflows/release-docker.yaml) and [release.yaml](https://github.com/kubeflow/spark-operator/blob/release-2.0/.github/workflows/release.yaml) were not triggered by this tag push event as expected. And I cannot figure out why, perhaps you could offer me some guidance.

@ChenYi015 It looks like according to this one GitHub workflow can't trigger another GitHub workflow: https://github.com/orgs/community/discussions/27028#discussioncomment-3254360

We might need to refactor our test to publish images in the same workflow where we push tag to the GitHub.
WDYT @ChenYi015 ?

**Comment by ChenYi015** [comment]
@andreyvelich Thanks for your help. I agree with you and I will refactor the workflows and put them in one workflow file. For the release of `v2.0.0-rc.0` version, since the `VERSION` file has already been modified, we will delete the tag and push it again manually to trigger the workflows to publish the docker image and draft the release.

**Pull request merged**
