### PR TITLE
Support driver and executor use different priority

### PR DESCRIPTION
**Pull request by Kevinz857**
### 🛑 Important:
Please open an issue to discuss significant work before you start. We appreciate your contributions and don't want your efforts to go to waste!

For guidelines on how to contribute, please review the [CONTRIBUTING.md](CONTRIBUTING.md) document.

## Purpose of this PR
This PR enhances the Spark Operator to support setting different priorities for driver and executor pods. This feature allows for more granular control over resource allocation and scheduling in Kubernetes clusters.

**Proposed changes:**
- Added support for specifying separate priorities for driver and executor pods in SparkApplication CRD
- Modified the controller logic to apply the specified priorities when creating driver and executor pods
- Updated relevant documentation to reflect the new feature

## Change Category
Indicate the type of change by marking the applicable boxes:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that could affect existing functionality)
- [x] Documentation update

### Rationale

In complex Kubernetes environments, there's often a need to prioritize Spark driver pods differently from executor pods. This change allows users to fine-tune their Spark application deployments, potentially improving overall cluster resource utilization and application performance.

## Checklist
Before submitting your PR, please review the following:

- [x] I have conducted a self-review of my own code.
- [x] I have updated documentation accordingly.
- [x] I have added tests that prove my changes are effective or that my feature works.
- [x] Existing unit tests pass locally with my changes.

### Additional Notes

This feature introduces new fields in the SparkApplication CRD. Users will need to update their CRD definitions to take advantage of this new functionality. Backward compatibility is maintained for existing deployments.

### CODE REVIEW

**Comment by ChenYi015** [comment]
@Kevinz857 Thanks for the contribution! Could you target this PR to branch `master`, we can cherry-pick it to the release branch after it has been merged to master. Also, could you rebase this PR to kubeflow/master so that it can be reviewed more easily?

**Comment by Kevinz857** [comment]
I hope to submit an MR to spark-operator, supporting different priorities for Driver and Executor Pod, but which branch should I checkout as the development branch? After a rough look at the master branch, there is a big difference between it and the corresponding latest tag. We usually use the tag version v1beta2-1.6.x-3.5.0 ,but where is the corresponding branch?  @ChenYi015 Can you help me answer this question?

**Comment by Kevinz857** [comment]
> @Kevinz857 Thanks for the contribution! Could you target this PR to branch `master`, we can cherry-pick it to the release branch after it has been merged to master. Also, could you rebase this PR onto the branch `kubeflow/master` so it can be reviewed more easily?

👌🏻 Then I will develop based on the Master branch and submit MergeRequest.Thanks for ur replay

**Comment by Kevinz857** [comment]
> @Kevinz857 Thanks for the contribution! Could you target this PR to branch `master`, we can cherry-pick it to the release branch after it has been merged to master. Also, could you rebase this PR onto the branch `kubeflow/master` so it can be reviewed more easily?

@ChenYi015 I developed based on the v1beta2-1.6.x-3.5.0 tag version. Can I submit a Merge Request directly to the Master branch like this?

**Comment by ChenYi015** [comment]
> @ChenYi015 I developed based on the v1beta2-1.6.x-3.5.0 tag version. Can I submit a Merge Request directly to the Master branch like this?

This PR has some merge conflicts so you need to solve it first. The recommended way is to rebase your commits onto the master branch, then pick the commits as needed and solve the conflicts.

**Pull request closed without merging**
