### PR TITLE
fixed docker image tag and updated chart docs

### PR DESCRIPTION
**Pull request by AndrewChubatiuk**
now docker images are published with 'preview' tag. changed it to a app version from Chart.yaml

### CODE REVIEW

**Comment by vara-bonthu** [comment]
@AndrewChubatiuk , it looks like the PR description is missing. Could you please provide more details to help us review your changes effectively? 

**Purpose of the Change:** Why is this change necessary?
**Problem Addressed:** What issue are you encountering that this change resolves?
**Solution:** How does this change solve the problem?
**Impact of Not Merging:** What would be the consequences if this PR is not merged?
**Existing Workarounds:** Is there a current workaround for this issue, and if so, what are its drawbacks?

Thank you for contributing, and we look forward to your detailed response!

**Comment by AndrewChubatiuk** [comment]
updated

**Review by vara-bonthu — APPROVED** [review]
/approve

**Review by vara-bonthu — APPROVED** [review]
/lgtm

**Pull request merged**
