### PR TITLE
Minor fixes to e2e test `make` targets

### PR DESCRIPTION
**Pull request by Tom-Newton**
## Purpose of this PR
Make it a little easier to get started running the e2e tests.

**Proposed changes:**
- Correct a typo so now it matches the docs https://www.kubeflow.org/docs/components/spark-operator/developer-guide/#run-e2e-tests.
- Use `$(KIND)` so it uses the `kind` that was automatically installed rather than trying to find it on system path.

## Change Category
Indicate the type of change by marking the applicable boxes:

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that could affect existing functionality)
- [ ] Documentation update

## Checklist
Before submitting your PR, please review the following:

- [x] I have conducted a self-review of my own code.
- [x] I have updated documentation accordingly - I don't think there is need for an update. 
- [x] I have added tests that prove my changes are effective or that my feature works - I don't think this is applicable. 
- [x] Existing unit tests pass locally with my changes.

### CODE REVIEW

**Review by ChenYi015 — APPROVED** [review]

**Comment by ChenYi015** [comment]
@Tom-Newton Thanks for fixing this.

**Comment by ChenYi015** [comment]
There is a go lint error introduced in recent commits which fails the code check CI and has already been fixed. Could you do a rebase? Will merge this PR when all CI workflow has passed.

**Comment by Tom-Newton** [comment]
Rebased for the CI fix

**Review by ChenYi015 — APPROVED** [review]

**Pull request merged**
