### PR TITLE
Update issue and pull request templates

### PR DESCRIPTION
**Pull request by ChenYi015**
## Proposed changes

- Update issue and pull request templates

### CODE REVIEW

**Comment by jacobsalway** [comment]
Put these in a test repo https://github.com/jacobsalway/test/issues/new/choose

**Review by jacobsalway — APPROVED** [review]
/lgtm

**Comment by ChenYi015** [comment]
> Not a blocker for approval but some small nitpicks:
> 
> * Referring to the operator as "the Spark operator"
> * We could add links to the Slack as well

Done.

**Review by jacobsalway — APPROVED** [review]
/lgtm

**Pull request merged**
