### PR TITLE
Add restartPolicy field to SparkApplication Driver/Executor initContainers CRDs

### PR DESCRIPTION
**Pull request by mschroering**
## Purpose of this PR
InitContainers can now specify a `restartPolicy` with a value of `Always` to make the init container act like a sidecar. This PR updates the CRDs to allow this field to be present. 

https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#lifecycle
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/

**Proposed changes:**
- Adds `restartPolicy` to `driver.initContainers` and `executor.initContainers` for both `SparkApplication` and `ScheduledSparkApplication`.

## Change Category
Indicate the type of change by marking the applicable boxes:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that could affect existing functionality)
- [ ] Documentation update

### Rationale

This allows users of the helm chart to set `restartPolicy: "Always"` for init containers on the executor and driver pods. 

## Checklist
Before submitting your PR, please review the following:

- [X] I have conducted a self-review of my own code.
- [X] I have updated documentation accordingly.
- [X] I have added tests that prove my changes are effective or that my feature works.
- [X] Existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by mjtieman** [comment]
+1 this will be very helpful.

**Comment by macnaughton** [comment]
+1 as well, we could use this

**Comment by GeorgiiKolpakov** [comment]
Good feature, would love to use it for our logging sidecar

**Review by vara-bonthu — APPROVED** [review]
LGTM

@yuchaoran2011 FYI

**Review by vara-bonthu — APPROVED** [review]
LGTM

**Review by yuchaoran2011 — APPROVED** [review]
/lgtm

**Pull request merged**
