### PR TITLE
Add ChenYi015 as spark-operator reviewer

### PR DESCRIPTION
**Pull request by ChenYi015**
### 🛑 Important:
Please open an issue to discuss significant work before you start. We appreciate your contributions and don't want your efforts to go to waste!

For guidelines on how to contribute, please review the [CONTRIBUTING.md](CONTRIBUTING.md) document.

## Purpose of this PR
Provide a clear and concise description of the changes. Explain the motivation behind these changes and link to relevant issues or discussions.

**Proposed changes:**
- Add myself @ChenYi015 as spark-operator reviewer

## Change Category
Indicate the type of change by marking the applicable boxes:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that could affect existing functionality)
- [ ] Documentation update

### Rationale

I am currently a member of Kubeflow organization. 

Contributed PRs: https://github.com/kubeflow/spark-operator/pulls?q=is%3Apr+author%3AChenYi015

## Checklist
Before submitting your PR, please review the following:

- [ ] I have conducted a self-review of my own code.
- [ ] I have updated documentation accordingly.
- [ ] I have added tests that prove my changes are effective or that my feature works.
- [ ] Existing unit tests pass locally with my changes.

### CODE REVIEW

**Review by yuchaoran2011 — CHANGES_REQUESTED** [review]
@ChenYi015 After discussions with fellow maintainers, we agree that your contributions should be recognized. We look forward to seeing you take on greater responsibility in the management of the repo over time. Let's do it step by step following the kubeflow guidelines: https://www.kubeflow.org/docs/about/contributing/#owners. As a start, could you update the PR to add yourself under `reviewers`? Then we can include you in the approvers list after a period of sustained contributions.

**Review by vara-bonthu — APPROVED** [review]

**Review by yuchaoran2011 — APPROVED** [review]
/lgtm

**Review by andreyvelich — COMMENTED** [review]
Thank you for your great contributions @ChenYi015 and congratulations to become Spark Operator maintainer 🎉

**Pull request merged**
