### PR TITLE
FEATURE: add cli argument to modify controller workqueue ratelimiter

### PR DESCRIPTION
**Pull request by ImpSy**
## Purpose of this PR

Add the capacity to customize the controller workqueue ratelimiter and remove a potential bug on high usage cluster 

**Proposed changes:**
- cli argument to modify the default controller-runtime workqueue ratelimiter
- Keep the default value (from controller-runtime) in the code but set them in the chart

## Change Category
Indicate the type of change by marking the applicable boxes:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that could affect existing functionality)
- [x] Documentation update

#### 1- controler-runtime uses `workqueue.DefaultControllerRateLimiter` by default which has a rather low BucketRatelimiter
With only 10 QPS and 100 Bucket max size we easily reach those number, before migrating to `controller-runtime` the value was actually 50/500 (https://github.com/kubeflow/spark-operator/commit/0dc641bd1d7d262e4a8c5564c926fc4716bcf722#diff-915090b1cf1857dc448319dbbbc11699ba40e674744723a5772a4624a1c79282L59)

#### 2- BucketRatelimiter does not have a max delay
We encounter a bug on a high usage cluster a few years ago where we discover that `BucketRatelimiter` rely on `golang.org/x/time/rate` `Limiter.Reserve()` function that is not upperBound:
- If QPS > Bucket max size then the rateLimiter return `rate.InfDuration`

Being able to set a MaxDelay fix this

## Checklist
Before submitting your PR, please review the following:

- [X] I have conducted a self-review of my own code.
- [X] I have updated documentation accordingly.
- [ ] I have added tests that prove my changes are effective or that my feature works.
- [X] Existing unit tests pass locally with my changes.

### Additional Notes

This changed has been implemented on our fork for almost 2 years -> https://github.com/spotinst/spark-on-k8s-operator/pull/5

### CODE REVIEW

**Review by vara-bonthu — COMMENTED** [review]
Thank you for the contribution! The PR looks good to me, except pending resolution of the comment. 

We’re planning to run some load tests in v2 with this change to evaluate if it improves performance and whether we actually need a queue-per-app solution.

Thanks, @ImpSy!

**Comment by ImpSy** [comment]
@vara-bonthu @ChenYi015 Added the documentation to the charts like you wanted
And thanks for the review 🙏

**Review by vara-bonthu — APPROVED** [review]
/approve

wait for another approval

**Review by ChenYi015 — APPROVED** [review]

**Pull request merged**
