### PR TITLE
Update who-is-using

### PR DESCRIPTION
**Pull request by adityasundaramurthy-maersk**

### CODE REVIEW

**Comment by zevisert** [comment]
PRs updating who-is-using can be merged to clean up the backlog of open MRs:
- #1808 
- #1795 
- #1615
- #1449

**Review by vara-bonthu — APPROVED** [review]
/lgtm

**Review by yuchaoran2011 — APPROVED** [review]
/lgtm

**Review by yuchaoran2011 — COMMENTED** [review]
/approve

**Pull request merged**
