### PR TITLE
Add scaffold for Yunikorn batch scheduler

### PR DESCRIPTION
**Pull request by jacobsalway**
### 🛑 Important:
Please open an issue to discuss significant work before you start. We appreciate your contributions and don't want your efforts to go to waste!

For guidelines on how to contribute, please review the [CONTRIBUTING.md](CONTRIBUTING.md) document.

## Purpose of this PR

Add an initial scaffold for a Yunikorn batch scheduler implementation. Splitting the PRs so I can incrementally finish work without leaving a mega PR to be reviewed.

Ref https://github.com/kubeflow/spark-operator/issues/2098

## Change Category
Indicate the type of change by marking the applicable boxes:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that could affect existing functionality)
- [ ] Documentation update

## Checklist
Before submitting your PR, please review the following:

- [x] I have conducted a self-review of my own code.
- [x] I have updated documentation accordingly.
- [x] I have added tests that prove my changes are effective or that my feature works.
- [x] Existing unit tests pass locally with my changes.

### Additional Notes

Will close https://github.com/kubeflow/spark-operator/pull/2042 once I've got that functionality merged in separate PRs

### CODE REVIEW

**Review by vara-bonthu — COMMENTED** [review]
Thanks for the PR @jacobsalway . This is looks good to me. 

It would be great to add some examples, documentation, and unit tests for using YuniKorn with the Spark Operator.

**Comment by jacobsalway** [comment]
@vara-bonthu I'm happy to put everything under one PR with docs, test etc. but thought it might be easier to split the work into separate PRs under this issue to avoid draft PRs sitting around for a while https://github.com/kubeflow/spark-operator/issues/2098

**Comment by ChenYi015** [comment]
Hi @jacobsalway , this work is great. I have modified the batch scheduler framework in #2072, and we should release v2.0.0-rc.0 soon, so would you mind rebase your work on this new 2.0 version.

**Comment by jacobsalway** [comment]
Hey @ChenYi015 once your controller runtime PR is merged to `release-2.0` I'll rebase and retarget my PR

**Pull request closed without merging**
