### PR TITLE
Update the process to build api-docs, generate CRD manifests and code

### PR DESCRIPTION
**Pull request by ChenYi015**
## Purpose of this PR

**Proposed changes:**

- Update Makefile by adding some useful targets
- Generate RBAC, CustomResourceDefinition and WebhookConfiguration manifests by `make manifests`, `controller-gen` will be automatically installed into `bin` directory if needed
- Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations by `make generate`, `controller-gen` will be automatically installed into `bin` directory if needed
- Update api-docs and related action workflow, `make build-api-docs` will automatically install `gen-crd-api-reference-docs` under `bin` directory and then used it to generate docs, no need to build docker image locally anymore.
- Add `bin/` to `.gitignore`

## Change Category
Indicate the type of change by marking the applicable boxes:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that could affect existing functionality)
- [x] Documentation update

### Rationale

Add some usefule targets to Makefile, the availabe targets are as follows:

```shell
$ make                              

Usage:
  make <target>

General
  help             Display this help.

Development
  manifests        Generate CustomResourceDefinition, RBAC and WebhookConfiguration manifests.
  generate         Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
  update-crd       Update CRD files in the Helm chart.
  clean            Clean up caches and output.
  go-fmt           Run go fmt against code.
  go-vet           Run go vet against code.
  lint             Run golangci-lint linter.
  lint-fix         Run golangci-lint linter and perform fixes.
  unit-test        Run go unit tests.
  e2e-test         Run go integration tests.

Build
  build-operator   Build spark-operator binary.
  build-sparkctl   Build sparkctl binary.
  install-sparkctl  Install sparkctl binary.
  clean-sparkctl   Clean sparkctl binary.
  build-api-docs   Build api documentaion.
  docker-build     Build docker image with the operator.
  docker-push      Push docker image with the operator.
  docker-buildx    Build and push docker image for the operator for cross-platform support.

Helm
  helm-unittest    Run Helm chart unittests.
  helm-lint        Run Helm chart lint test.
  helm-docs        Generates markdown documentation for helm charts from requirements and values files.

Deployment
  install          Install CRDs into the K8s cluster specified in ~/.kube/config.
  uninstall        Uninstall CRDs from the K8s cluster specified in ~/.kube/config. Call with ignore-not-found=true to ignore resource not found errors during deletion.
  deploy           Deploy controller to the K8s cluster specified in ~/.kube/config.
  undeploy         Undeploy controller from the K8s cluster specified in ~/.kube/config. Call with ignore-not-found=true to ignore resource not found errors during deletion.

Dependencies
  kustomize        Download kustomize locally if necessary.
  controller-gen   Download controller-gen locally if necessary.
  kind             Download kind locally if necessary.
  envtest          Download setup-envtest locally if necessary.
  golangci-lint    Download golangci-lint locally if necessary.
  gen-crd-api-reference-docs  Download gen-crd-api-reference-docs locally if necessary.
```

## Checklist
Before submitting your PR, please review the following:

- [x] I have conducted a self-review of my own code.
- [ ] I have updated documentation accordingly.
- [ ] I have added tests that prove my changes are effective or that my feature works.
- [x] Existing unit tests pass locally with my changes.

### CODE REVIEW

**Review by vara-bonthu — APPROVED** [review]
@ChenYi015 Great work on updating the process for building API documentation and generating CRD manifests. 
This will streamline the workflow and improve maintainability. 

PR looks good to me. 

@yuchaoran2011

**Comment by ChenYi015** [comment]
@yuchaoran2011 Could you merge this PR first? This will make the development process much more easier.

**Review by yuchaoran2011 — COMMENTED** [review]
Neat improvements! Common tasks will be much more convenient to perform. Need a chart version bump and then should be good to merge

**Comment by ChenYi015** [comment]
> Neat improvements! Common tasks will be much more convenient to perform. Need a chart version bump and then should be good to merge

@yuchaoran2011 Rebased and bumped the chart version.

**Review by yuchaoran2011 — APPROVED** [review]
/lgtm

**Pull request merged**
